version: '3.7'

volumes:
  local_mysql_data: {}
  local_mysql_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: apps_local_django
    container_name: django
    depends_on:
      - mysql
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.mysql
    ports:
      - "5000:5000"
    networks:
      - gropoz-network
    command: /start

  mysql:
    build:
      context: .
      dockerfile: ./compose/production/mysql/Dockerfile
    image: apps_production_mariadb
    container_name: mysql
    volumes:
      - local_mysql_data:/var/lib/mysql:z
      - local_mysql_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.mysql
    networks:
      - gropoz-network
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - gropoz-network

  celery_worker:
    <<: *django
    image: apps_local_celery_worker
    container_name: apps_local_celery_worker
    depends_on:
      - redis
    ports: [ ]
    command: /start-celery-worker
    networks:
      - gropoz-network

  celery_beat:
    <<: *django
    image: apps_local_celery_beat
    container_name: apps_local_celery_beat
    depends_on:
      - redis
    ports: [ ]
    command: /start-celery-beat
    networks:
      - gropoz-network

networks:
    gropoz-network:
      external: true

